Updating circle and adding a .nvmrc for older npm support

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,140 +1,418 @@
-# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
+version: 2.1
+
+# To easily configure jobs here, parameters are set up below. Since we are
+# typically not calling this workflow via pipelines, consider changing the
+# defaults here for any permanent configuration you need to do on a project
+# by project basis.
+parameters:
+  php-version:
+    description: major.minor version number for php version to use.
+    type: string
+    # This value must be only a major.minor version is pantheon is the
+    # host-variant as the build-tool images do not support major.minor.patch
+    # version numbers.
+    default: "7.4"
+  tz:
+    description: The timezone definition.
+    type: string
+    default: "America/Chicago"
+  host-variant:
+    description: A string representing a site's host. EX acquia, pantheon
+    type: string
+    default: "pantheon"
+  docroot:
+    description: "Where composer installs drupal."
+    default: "web"
+    type: string
+  artifact_workspace:
+    description: "Where the build stores the built artifact temporarly."
+    default: "/tmp/build"
+    type: string
+
+# These are the directories that will be saved between builds and deploys.
+# Change these if the list below needs different folders. Directory names are
+# relative to the project root.
+persisting_dirs: &persisting_dirs
+  - << pipeline.parameters.docroot >>
+  - vendor
+  - drush
+# - node_modules
+
+
+env: &env
+  #########################
+  # MANDITORY CONFIGURATION
+  #
+  # Set these either here in your config.yml or in CircleCI project Enviornment
+  # variables.
+  #########################
+
+  # A github access token so the bot user can comment back on the commit.
+  #
+  # GITHUB_TOKEN: 12345678790abcdef
+
+  ############################
+  # ACQUIA SPECIFIC SETTINGS
+  ############################
+
+  # Acquia git repo url.
+  #
+  # ACQUIA_REPO: sitename@svn-21939.prod.hosting.acquia.com:sitename.git
+
+  # Cloud API Realm. Usually "prod" or "devcloud".
+  #
+  # See: https://docs.acquia.com/acquia-cloud/api#realm
+  #
+  # ACQUIA_REALM: prod
+
+  ############################
+  # PANTHEON SPECIFIC SETTINGS
+  ############################
+
+  # TERMINUS_TOKEN: The Pantheon machine token
+
+  ########################
+  # OPTIONAL CONFIGURATION
+  ########################
+
+  # An arbitrary email that will be used as the committer when building the
+  # artifact.
+  #
+  # Default: bender@fourkitchens.com
+  #
+  # GIT_EMAIL: bender@fourkitchens.com
+
+  # Name of the Acquia or Pantheon site to deploy to.
+  #
+  # Default: github repo name
+  #
+  # SITE_NAME: my_site
+
+  # Environment to get canonical database and files from
+  #
+  # Possible Values:
+  # For Acquia: dev, test prod
+  # For Pantheon: dev, test, live
+  #
+  # Default: "prod" on Acquia. "live" on Pantheon
+  #
+  # CANONICAL_ENV: dev
+
+  # Script used to sanatize databases. Only used when CANONICAL_ENV is not dev.
+  #
+  # Default: empty
+  #
+  # SANATIZE_SCRIPT: ./vendor/fourkitchens/project_ci/scripts/sanatize-db
+
+  #####################################
+  # OPTIONAL CONFIGURATION FOR PANTHEON
+  #####################################
+
+  # Build CI multidevs on every commit on Pantheon. This way you get the ci-*
+  # environments. This may be useful for visual regression testing or workflows
+  # without PRs.
+  #
+  # Possible Values: YES, NO
+  #
+  # Default: NO
+  #
+  # CI_BUILD: YES
+
+  # Define the main branch releases are cut from.
+  #
+  # Default: "main" if the branch it exists, "master" otherwise.
+  #
+  # MAIN_BRANCH: master
+
+  # Define the development branch where active development happens on github.
+  # This branch is used most in gitflow development patterns.
+  #
+  # Default: develop
+  #
+  # DEVELOPMENT_BRANCH: dev
+
+  # Re-sync content for multidevs every time a push is made to Pantheon.
+  #
+  # Possible Values: NO, YES
+  #
+  # Default: NO
+  #
+  # REBUILD_MULTIDEV_ENV_EVERY_PUSH: YES
+
+  # Re-sync content for the Github development multidev every time a push is
+  # made to Pantheon.
+  #
+  # Possible Values: NO, YES
+  #
+  # Default: NO
+  #
+  # REBUILD_DEVELOPMENT_ENV_EVERY_PUSH: YES
+
+  # Define the name of the multidev used for the Github development branch. Must
+  # follow the multidev naming conventions for Pantheon.
+  #
+  # Default: github-dev
+  #
+  # DEVELOPMENT_ENV: circleci
+
+
+  ###########################
+  # STUFF THAT DOESN'T CHANGE
+  ###########################
+  HOST_VARIANT: << pipeline.parameters.host-variant >>
+  DATE_TIMEZONE: << pipeline.parameters.tz >>
+  DOCROOT: << pipeline.parameters.docroot >>
+  TERM: xterm
+
 defaults: &defaults
-  docker:
-    - image: quay.io/pantheon-public/build-tools-ci:nodejs
-  working_directory: ~/example_drops_8_composer
+  executor:
+    name: php/default
+    tag: << pipeline.parameters.php-version >>
+  working_directory: ~/project
   environment:
-    #=========================================================================
-    # In addition to the environment variables defined in this file, also
-    # add the following variables in the Circle CI UI.
-    #
-    # See: https://circleci.com/docs/2.0/env-vars/
-    #
-    # TERMINUS_SITE:  Name of the Pantheon site to run tests on, e.g. my_site
-    # TERMINUS_TOKEN: The Pantheon machine token
-    # GITHUB_TOKEN:   The GitHub personal access token
-    # GIT_EMAIL:      The email address to use when making commits
-    #
-    # TEST_SITE_NAME: The name of the test site to provide when installing.
-    # ADMIN_PASSWORD: The admin password to use when installing.
-    # ADMIN_EMAIL:    The email address to give the admin when installing.
-    #=========================================================================
-    TZ: "/usr/share/zoneinfo/America/Chicago"
+    <<: *env
 
-    # The variables below usually do not need to be modified.
-
-    #======================================================================================================================================
-    # Circle CI 2.0 does not yet expand environment variables so they have to be manually EXPORTed
-    # Once environment variables can be expanded the variables below can be uncommented and the EXPORTs in set-up-globals.sh can be removed
-    # See: https://discuss.circleci.com/t/unclear-how-to-work-with-user-variables-circleci-provided-env-variables/12810/11
-    # See: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
-    # See: https://discuss.circleci.com/t/circle-2-0-global-environment-variables/8681
-    #======================================================================================================================================
-
-    NOTIFY: 'scripts/github/add-commit-comment {project} {sha} "Created multidev environment [{site}#{env}]({dashboard-url})." {site-url}'
-    ADMIN_USERNAME: admin
-    # BUILD_TOOLS_VERSION: ^2.0.0-alpha4
-    TERM: dumb
-
-version: 2
 jobs:
-    # @todo: common initialization: 'composer install' for the site-under-test
-    build:
-        <<: *defaults
-        steps:
-            - checkout
+  # Static Testing. This will run independently of a build to fail quickly.
+  static_tests:
+    <<: *defaults
+    steps:
+      - setup-project
+      - run:
+          name: run static tests
+          command: |
+            if [ -f "./.circleci/scripts/test/static" ]; then
+              ./.circleci/scripts/test/static
+            else
+              ./vendor/fourkitchens/project_ci/scripts/test/static
+            fi
 
-            - restore_cache:
-                keys:
-                    - composer-cache
-                    - terminus-install
+  # Job used to create what will be committed to the Artifact.
+  #
+  # You will have all the dependency managers installed here in case you need
+  # them.
+  build:
+    <<: *defaults
+    steps:
+      - setup-project
+      - run:
+          name: run PHP build step
+          command: |
+            if [ -f "./.circleci/scripts/build/php" ]; then
+              ./.circleci/scripts/build/build/php
+            else
+              ./vendor/fourkitchens/project_ci/scripts/build/php
+            fi
+      - run:
+          name: run theme build step
+          command: |
+            if [ -f "./.circleci/scripts/build/theme" ]; then
+              ./.circleci/scripts/build/theme
+            else
+              ./vendor/fourkitchens/project_ci/scripts/build/theme
+            fi
+      - persist_to_workspace:
+          root: .
+          paths: *persisting_dirs
 
-            - run:
-                # Set TERMINUS_ENV and related environment variables.
-                # https://github.com/pantheon-systems/docker-build-tools-ci/blob/1.x/scripts/set-environment
-                name: environment
-                command: /build-tools-ci/scripts/set-environment
+  # Job used to deploy to a remote environment.
+  #
+  # This could be as simple as pushing the artifact to a remote git repo or as
+  # complicated as building a remote environment to push to. This job will not
+  # be run if the host-variant parameter is set to "pantheon"
+  deploy:
+    <<: *defaults
 
-            - run:
-                name: run composer install to get the vendor directory
-                command: composer install
+    steps:
+      - restore-project:
+          workspace_root: << pipeline.parameters.artifact_workspace >>
+      - run:
+          name: Deploy the code
+          command: |
+            if [ -f "./.circleci/scripts/deploy" ]; then
+              ./.circleci/scripts/deploy
+            else
+              ./vendor/fourkitchens/project_ci/scripts/deploy
+            fi
 
-            - save_cache:
-                key: composer-cache
-                paths:
-                    - $HOME/.composer/cache
+  # Job used to deploy to pantheon.
+  #
+  # This job is special because pantheon employs a special docker container and
+  # the use of terminus with build tools which expect a very specific
+  # environment configuration. To enable this job, set the host-variant
+  # parameter to "pantheon".
+  deploy_to_pantheon:
+    <<: *defaults
+    docker:
+      # quay.io/pantheon-public/build-tools-ci:8.x-php${PHPVERSION}
+      - image: quay.io/pantheon-public/build-tools-ci:8.x-php<< pipeline.parameters.php-version >>
+    environment:
+      <<: *env
+      TZ: /usr/share/zoneinfo/<< pipeline.parameters.tz >>
+      NOTIFY: 'scripts/github/add-commit-comment {project} {sha} "Created multidev environment [{site}#{env}]({dashboard-url})." {site-url}'
+      TERM: dumb
+      # BUILD_TOOLS_VERSION: ^2.0.0-alpha4
+    steps:
+      - checkout
+      - restore-project:
+          workspace_root: << pipeline.parameters.artifact_workspace >>
+      - run:
+          name: Upgrade composer
+          command: composer self-update
+      - run:
+          name: setup-environment-vars
+          command: |
+            if [ -f "./.circleci/scripts/set-environment" ]; then
+              ./.circleci/scripts/set-environment
+            else
+              ./vendor/fourkitchens/project_ci/scripts/set-environment
+            fi
+      - run:
+          name: deploy to Pantheon
+          command: |
+            if [ -f "./.circleci/scripts/deploy" ]; then
+              ./.circleci/scripts/deploy
+            else
+              ./vendor/fourkitchens/project_ci/scripts/pantheon/deploy
+            fi
+          no_output_timeout: 30m
 
-            - save_cache:
-                key: terminus-install
-                paths:
-                    - $(TERMINUS_PLUGINS_DIR:-~/.terminus/plugins)
-
-            - run:
-                name: lint php code for syntax errors
-                command: composer -n lint
-
-            - run:
-                name: check coding standards
-                command: composer -n code-sniff
-
-            - run:
-                name: run unit tests
-                command: composer -n unit-test
-
-    build_deploy_and_test:
-        <<: *defaults
-        steps:
-            - checkout
-
-            - restore_cache:
-                keys:
-                    - composer-cache
-                    - terminus-install
-
-            - run:
-                # Set TERMINUS_ENV and related environment variables.
-                # https://github.com/pantheon-systems/docker-build-tools-ci/blob/1.x/scripts/set-environment
-                name: dependencies
-                command: /build-tools-ci/scripts/set-environment
-
-            - run:
-                name: install dev dependencies, build assets, etc.
-                command: ./.circleci/scripts/pantheon/01-prepare
-
-            - run:
-                name: build assets
-                command: composer -n build-assets
-
-            - run:
-                name: prepare database for site-under test
-                command: ./.circleci/scripts/pantheon/02-init-site-under-test-clone-existing
-                # command: ./.circleci/scripts/pantheon/02-init-site-under-test-reinstall-new
-
-            - run:
-                name: run composer install again to get dev dependencies
-                command: composer install
-
-            #- run:
-            #    name: run functional tests with Behat
-            #    command: ./tests/scripts/run-behat
-
-            - run:
-                name: post-test actions
-                command: ./.circleci/scripts/pantheon/03-post-test
-
-            - run:
-                name: handle merge to master (if needed)
-                command: ./.circleci/scripts/pantheon/04-merge-master
-
-            - run:
-                name: remove transient test fixtures
-                command: ./.circleci/scripts/pantheon/09-cleanup-fixtures
+  # Run this on one of the main branches to push a release back to github.
+  #
+  # This usually will do things like create a change log and bump the version
+  # on the source repository.
+  release:
+    <<: *defaults
+    steps:
+      - setup-project
+      - run:
+          name: Publish a Release
+          command: |
+            if [ -f "./.circleci/scripts/release" ]; then
+              ./.circleci/scripts/release
+            else
+              ./vendor/fourkitchens/project_ci/scripts/release
+            fi
 
 workflows:
   version: 2
-  build_and_test:
+  build-deploy-pantheon:
+    when:
+      equal: [ pantheon, << pipeline.parameters.host-variant >> ]
     jobs:
-      # Install dev dependencies and do simple tests (sniff, unit tests, etc.)
+      - static_tests
       - build
-      # Build deploy and test on target platform
-      - build_deploy_and_test
+      # This is doesn't set the branch restraints because multidevs can be
+      # created using any branch.
+      - deploy_to_pantheon:
+          requires:
+            - static_tests
+            - build
+      - release:
+          requires:
+          - deploy_to_pantheon
+          filters:
+            branches:
+              only:
+                - 'main'
+                - 'master'
+  build-deploy-acquia:
+    when:
+      not:
+        equal: [ pantheon, << pipeline.parameters.host-variant >> ]
+    jobs:
+      - static_tests
+      - build
+      - deploy:
+          requires:
+            - static_tests
+            - build
+          filters:
+            branches:
+              only:
+                - main
+                - master
+                - develop
+                - /release-.*/
+      - release:
+          requires:
+          - deploy
+          filters:
+            branches:
+              only:
+                - 'main'
+                - 'master'
+
+###### Please do not change things in the commands without contributing back.
+orbs:
+  node: circleci/node@4.1.0
+  php: circleci/php@1.1.0
+commands:
+  install-node-from-nvmrc:
+    description: Workaround for installing node on projects with .nvmrc files.
+    steps:
+      # Work around for node install issue. This happens because nvm checks
+      # to see if the version of node in the .nvmrc exists before it does
+      # anything else. Therefore, we have to remove the .nvmrc file before we
+      # install nvm, and then put it back. Afterwards, we set the version of
+      # node in the .nvmrc file as the default.
+      # see: https://github.com/CircleCI-Public/node-orb/issues/65
+      - run: "if [ -f \".nvmrc\" ]; then rm .nvmrc; fi"
+      - node/install
+      - run: "if git status --short | grep .nvmrc; then git checkout .nvmrc; else echo \"stable\" > .nvmrc; fi"
+      - run: nvm install
+      - run: nvm alias default `cat .nvmrc`
+      - run: node --version
+  install-project-dependency-managers:
+    description: setup composer and npm.
+    steps:
+      # Most projects require both composer and npm to be installed to do
+      # anything.
+      - php/install-composer
+      - install-node-from-nvmrc
+  install-project-dependencies:
+    description: install both npm and composer dependencies
+    steps:
+      - php/install-packages
+      # Lets install the node packages as they are defined by the lock file
+      # in the project.
+      - node/install-packages:
+          cache-path: ~/project/node_modules
+          override-ci-command: npm ci
+  setup-project:
+    description: setup php and node and download all dependencies for the project.
+    steps:
+      - checkout
+      - install-project-dependency-managers
+      - install-project-dependencies
+      - run:
+          name: Set up environment variables
+          command: |
+            if [ -f "./.circleci/scripts/set-environment" ]; then
+              ./.circleci/scripts/set-environment
+            elif [ -f "./vendor/fourkitchens/project_ci/set-environment" ]; then
+              ./vendor/fourkitchens/project_ci/set-environment
+            fi
+  restore-project:
+    description: Restore a Drupal project that was persisted from another job.
+    parameters:
+      workspace_root:
+        description: "Where to copy the workspace to"
+        default: "/tmp/build"
+        type: string
+    steps:
+      - checkout
+      - attach_workspace:
+          at: << parameters.workspace_root >>
+      # Rsync the build artifact pieces back into the project.
+      - run:
+          name: sync build artifact
+          command: |
+            if ! command -v rsync &> /dev/null
+            then
+              sudo apt-get update -y
+              sudo apt-get -y install rsync
+            fi
+            rsync -lrz << parameters.workspace_root >>/* .
+
+##### Feel free to alter the tasks below to point to your own tasks.
